set(_CATKIN_CURRENT_PACKAGE "control_develop")
set(control_develop_VERSION "0.0.0")
set(control_develop_MAINTAINER "hemingshan <hemingshan@todo.todo>")
set(control_develop_PACKAGE_FORMAT "2")
set(control_develop_BUILD_DEPENDS "geometry_msgs" "mav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(control_develop_BUILD_EXPORT_DEPENDS "geometry_msgs" "mav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(control_develop_BUILDTOOL_DEPENDS "catkin")
set(control_develop_BUILDTOOL_EXPORT_DEPENDS )
set(control_develop_EXEC_DEPENDS "geometry_msgs" "mav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(control_develop_RUN_DEPENDS "geometry_msgs" "mav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "trajectory_msgs")
set(control_develop_TEST_DEPENDS )
set(control_develop_DOC_DEPENDS )
set(control_develop_URL_WEBSITE "")
set(control_develop_URL_BUGTRACKER "")
set(control_develop_URL_REPOSITORY "")
set(control_develop_DEPRECATED "")